src/Forum_ASP.NET/Models/Comment.cs
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Forum_ASP.NET.Models
{
    public class Comment
    {
        [Key]
        public int CommentId { get; set; }
        public int DiscussionId { get; set; }
        //[Required]
        public string Content { get; set; }
        public string CommentAuthor { get; set; }
        public string CommentDate { get; set; }

        [ForeignKey("DiscussionId")]
        public virtual Discussion Discussion { get; set; }
    }
}

src/Forum_ASP.NET/Models/Discussion.cs
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Forum_ASP.NET.Models
{
    public class Discussion
    {
        [Key]
        public int DiscussionId { get; set; }
        public string DiscussionName { get; set; }
        public string Author { get; set; }
        public string CreatingDate { get; set; }
        public string LastDate { get; set; }
        public string FirstComment { get; set; }

        public virtual List<Comment> Comments { get; set; }

        public Discussion()
        {
            Comments = new List<Comment>();
        }
    }
}

src/Forum_ASP.NET/ViewModels/Roles/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_ASP.NET.ViewModels.Roles
{
    public class CreateViewModel
    {
        [Required]
        public string Rolename { get; set; }
        public string Description { get; set; }
    }
}

src/Forum_ASP.NET/ViewModels/Roles/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Forum_ASP.NET.ViewModels.Roles
{
    public class EditViewModel
    {
        [Required]
        public string Rolename { get; set; }
        public string Description { get; set; }
    }
}

src/Forum_ASP.NET/Controllers/DiscussionsController.cs
using Forum_ASP.NET.Models;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Storage;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Forum_ASP.NET.Controllers
{
	public class DiscussionsController : Controller
	{
		private ApplicationDbContext _context;

		public DiscussionsController( ApplicationDbContext context )
		{
			_context = context;
		}

		public IActionResult Index()
		{
			return View( _context.Discussions.ToList() );
		}

		public IActionResult Create()
		{
			return View();
		}

		public IActionResult CreateComment( int id )
		{
			Comment comment = new Comment()
			{
				DiscussionId = id,
			};

			return View( comment );
		}

		public async Task<ActionResult> Comment( int id )
		{
			var comment = await FindCommentsAsync( id );

			if ( comment == null )
			{
				return HttpNotFound();
			}
			return View( comment );
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create( Discussion discussion, Comment comment )
		{
			if ( ModelState.IsValid )
			{
				discussion.CreatingDate = DateTime.Now.ToString();
				discussion.LastDate = DateTime.Now.ToString();
				discussion.Author = User.GetUserName();
                comment.Content = discussion.FirstComment;
                comment.CommentDate = discussion.CreatingDate;
                comment.CommentAuthor = discussion.Author;
                _context.Discussions.Add( discussion );
				comment.DiscussionId = discussion.DiscussionId;
				_context.Comment.Add( comment );
				_context.SaveChanges();
				return RedirectToAction( "Index" );
			}

			return View( discussion );
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CreateComment( Comment comment )
		{
			if ( ModelState.IsValid )
			{
				comment.Discussion = await FindDiscussionAsync( comment.DiscussionId );
				comment.Discussion.LastDate = DateTime.Now.ToString();
				comment.CommentDate = DateTime.Now.ToString();
				comment.CommentAuthor = User.GetUserName();
				_context.Comment.Add( comment );
				_context.SaveChanges();
				return RedirectToAction( "Comment", new { id = comment.DiscussionId } );
			}

			return View( comment );
		}

        //Edit
        public async Task<ActionResult> Edit(int id)
        {
            Discussion discussion = await FindDiscussionAsync(id);
            if (discussion == null)
            {
                return HttpNotFound();
            }

            ViewBag.Items = GetAuthorsListItems(discussion.DiscussionId);
            return View(discussion);
        }

        //Comment Edit
        public async Task<ActionResult> CommentEdit( int id )
		{
			Comment comment = await FindCommentAsync( id );
			if ( comment == null )
			{
				return HttpNotFound();
			}

			ViewBag.Items = GetAuthorsListItems( comment.CommentId );
			return View( comment );
		}

        //Find Async for Edit
        private Task<Discussion> FindDiscussionAsync( int id )
		{
			return _context.Discussions.Include( c => c.Comments ).SingleOrDefaultAsync( discussion => discussion.DiscussionId == id );
		}

        //Find Async for Edit
        private Task<List<Comment>> FindCommentsAsync( int id )
		{
			return _context.Comment.Where( comment => comment.DiscussionId == id ).ToListAsync<Comment>();
		}

        //Find Async for CommentEdit
        private Task<Comment> FindCommentAsync(int id)
        {
            return _context.Comment.Include(c => c.Discussion).SingleOrDefaultAsync(comment => comment.CommentId == id);
        }

        //
        private IEnumerable<SelectListItem> GetAuthorsListItems( int selected = -1 )
		{
			var tmp = _context.Discussions.ToList();

			return tmp
					.OrderBy( discussion => discussion.LastDate )
					.Select( discussion => new SelectListItem
					{
						Text = String.Format( "{0}, {1}", discussion.DiscussionName, discussion.Author ),
						Value = discussion.CreatingDate.ToString(),
						Selected = discussion.DiscussionId == selected
					} );
		}

        //Edit Update 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int id, [Bind("DiscussionName", "CreatingDate", "LastDate", "Comments", "Author")] Discussion discussion)
        {
            discussion.DiscussionId = id;
            discussion.LastDate = DateTime.Now.ToString();
            _context.Discussions.Attach(discussion);
            _context.Entry(discussion).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //Comment Edit Upddate
        [HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> CommentUpdate( int id, [Bind( "Content", "CommentDate", "CommentAuthor", "DiscussionId", "CommentId")] Comment comment )
		{
            _context.Comment.Attach(comment);
            _context.Entry(comment).State = EntityState.Modified;
            comment.Discussion = await FindDiscussionAsync(comment.DiscussionId);
            comment.Discussion.LastDate = DateTime.Now.ToString();
			await _context.SaveChangesAsync();
            return RedirectToAction("Comment", new { id = comment.DiscussionId });
        }
	}
}

src/Forum_ASP.NET/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Mvc;
using Forum_ASP.NET.ViewModels.Roles;
using Forum_ASP.NET.Models;

namespace Forum_ASP.NET.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationDbContext _context;

        public RolesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Roles.ToList());
        }

        public IActionResult Manage()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete()
        {
            return View();

        }
        public IActionResult Edit()
        {
            return View();

        }

        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(CreateViewModel model)
        {
            try
            {
                _context.Roles.Add(new Microsoft.AspNet.Identity.EntityFramework.IdentityRole()
                {
                    Name = model.Rolename
                });
                _context.SaveChanges();
                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

            //if (ModelState.IsValid)
            //{
            //    var result = new IdentityRole { Name = model.Rolename };
            //    if (result)
            //    {
            //        return RedirectToAction(nameof(RolesController.Index), "Index");
            //    }
            //    AddErrors(result);
            //}

            //// If we got this far, something failed, redisplay form
            //return View(model);

        }

        public ActionResult Delete(string RoleName)
        {
            var thisRole = _context.Roles.Where(r => r.Name.Equals(RoleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();
            _context.Roles.Remove(thisRole);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            var thisRole = _context.Roles.Where(r => r.Name.Equals(roleName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Microsoft.AspNet.Identity.EntityFramework.IdentityRole role)
        {
            try
            {
                _context.Entry(role).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

src/Forum_ASP.NET/Views/Discussions/Comment.cshtml
@using System.Security.Claims
@model IEnumerable<Forum_ASP.NET.Models.Comment>


@{
    ViewBag.Title = "Comments";
}

<h2>@ViewData["Title"]</h2>

@if (User.IsSignedIn())
{
    if (User.Identity.Name.Equals(Model.First().CommentAuthor))
    {
    <p>
        <a class="btn btn-default" asp-action="CreateComment" asp-controller="Discussions" asp-route-id="@Model.First().DiscussionId">New Comment</a>
        <a class="btn btn-default" asp-action="Edit" asp-controller="Discussions" asp-route-id="@Model.First().DiscussionId">Edit</a>
    </p>
    }
    else
    {
    <p>
        <a class="btn btn-default" asp-action="CreateComment" asp-controller="Discussions" asp-route-id="@Model.First().DiscussionId">New Comment</a>
    </p>
    }
}
else { }

<table>
    <tr>
        <th width="1%"></th>
        <th width="20%">Author</th>
        <th width="60%">Comment</th>
        <th width="20%">Date</th>
    </tr>
    @foreach (var item in Model.OrderBy(item => item.CommentDate))
    {
        <tr>
            <td>
                @if (User.IsSignedIn())
                {
                    if (User.Identity.Name.Equals(item.CommentAuthor))
                    {
                    <a class="rowLink" asp-action="CommentEdit" asp-controller="Discussions" asp-route-id="@item.CommentId"></a>
                    }
                    else
                    {
                        <a class="rowLink"></a>
                    }
                }
                else
                {
                    <a class="rowLink"></a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommentAuthor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CommentDate)
            </td>
        </tr>
    }

</table>

src/Forum_ASP.NET/Views/Discussions/CommentEdit.cshtml
@model Forum_ASP.NET.Models.Comment

@{
    ViewBag.Title = "Comment Edit";
}

<h2>@ViewData["Title"]</h2>

<div>
    <form asp-controller="Discussions" asp-action="CommentUpdate" method="post" asp-route-id="@Model.CommentId">
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Content"></label>
            <textarea asp-for="Content" class="form-control" ></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="CommentDate" class="form-control" />
            <span asp-validation-for="CommentDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="CommentAuthor" class="form-control" />
            <span asp-validation-for="CommentAuthor" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="DiscussionId" class="form-control" />
            <span asp-validation-for="DiscussionId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="CommentId" class="form-control" />
            <span asp-validation-for="CommentId" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-default" value="Save" />
    </form>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

src/Forum_ASP.NET/Views/Discussions/Create.cshtml
@model Forum_ASP.NET.Models.Discussion

@{
    ViewBag.Title = "New Discussion";
}

<h2>@ViewData["Title"]</h2>
    
<form asp-controller="Discussions" asp-action="Create" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <div class="form-group">

            <label asp-for="DiscussionName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="DiscussionName" class="form-control" />
                <span asp-validation-for="DiscussionName" class="text-danger"></span>
            </div>

            <label asp-for="FirstComment" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="FirstComment" class="form-control"><</textarea>
                <span asp-validation-for="FirstComment" class="text-danger"></span>
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

src/Forum_ASP.NET/Views/Discussions/CreateComment.cshtml
@model Forum_ASP.NET.Models.Comment

@{
    ViewBag.Title = "New Comment";
}

<h2>@ViewData["Title"]</h2>
    
<form asp-controller="Discussions" asp-action="CreateComment" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <div class="form-group">

            <label asp-for="Content" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <textarea asp-for="Content" class="form-control" ><</textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
                <input type="hidden" asp-for="DiscussionId" />
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CreateComment" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

src/Forum_ASP.NET/Views/Discussions/Edit.cshtml
@model Forum_ASP.NET.Models.Discussion

@{
    ViewBag.Title = "Edit";
}

<h2>@ViewData["Title"]</h2>

<div>
    <form asp-controller="Discussions" asp-action="Update" method="post" asp-route-id="@Model.DiscussionId">
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="DiscussionName"></label>
            <input asp-for="DiscussionName" class="form-control" />
            <span asp-validation-for="DiscussionName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="CreatingDate" class="form-control" />
            <span asp-validation-for="CreatingDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="LastDate" class="form-control" />
            <span asp-validation-for="LastDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-default" value="Save" />
    </form>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

src/Forum_ASP.NET/Views/Discussions/Index.cshtml
@using System.Security.Claims
@model IEnumerable<Forum_ASP.NET.Models.Discussion>
@{
    ViewBag.Title = "Discussions";
}

<h2>@ViewData["Title"]</h2>

@if (User.IsSignedIn())
{
<p>
    <a class="btn btn-default" asp-action="Create" asp-controller="Discussions">New Discussion</a>
    <a class="btn btn-default" asp-action="Index" asp-controller="Roles">Roles</a>
</p>
}
else { }

<table>
    <tr>
        <th width="1%"></th>
        <th width="20%">Name</th>
        <th width="20%">Author</th>
        <th width="20%">Last Date</th>
        <th width="20%">Creating Date</th>
    </tr>

    @foreach (var item in Model.OrderByDescending(item => item.LastDate))
    {
        <tr>
            <td>
                <a class="rowLink" asp-action="Comment" asp-controller="Discussions" asp-route-id="@item.DiscussionId"></a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiscussionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatingDate)
            </td>
        </tr>
    }
</table>